version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
  token:
    image: token:v1
    ports:
      - "8080:8080"
    depends_on:
      - redis
    container_name: token_v1
    stdin_open: true
    tty: true
    build: .
    restart: on-failure

    links:
      - redis
